### ISSUE TITLE
Verify bot?

### ISSUE THREAD

**Issue by 0Charliecat** [zastrixarundell/Catlixir#10]

**Comment by zastrixarundell** [comment]
Started the verification process, will tell when it's finished. 

![image](https://user-images.githubusercontent.com/30195425/96093268-3c235d80-0ecc-11eb-9b85-70534149e075.png)

**Comment by 0Charliecat** [comment]
😸

**Comment by zastrixarundell** [comment]
It's been approved so I'm closing the ticket.

**Comment by 0Charliecat** [comment]
Thanks
